Use of ip address in boolean context for python3
Missing __bool__ for python3 lead to a traceback:
OverflowError: cannot fit 'int' into an index-sized integer
Thanks Christian for discovering this.